# Generated by Django 2.2.6 on 2019-10-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryid', models.IntegerField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, db_column='CategoryName', max_length=45, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=100, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerid', models.IntegerField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('customername', models.CharField(db_column='CustomerName', max_length=45)),
                ('contactname', models.CharField(blank=True, db_column='ContactName', max_length=45, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=45, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=45, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=45, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('orderdetailid', models.IntegerField(db_column='OrderDetailID', primary_key=True, serialize=False)),
                ('orderid', models.CharField(blank=True, db_column='OrderID', max_length=45, null=True)),
                ('productid', models.CharField(blank=True, db_column='ProductID', max_length=45, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
            ],
            options={
                'db_table': 'orderdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.IntegerField(db_column='OrderID', primary_key=True, serialize=False)),
                ('customerid', models.IntegerField(blank=True, db_column='CustomerID', null=True)),
                ('employeeid', models.IntegerField(blank=True, db_column='EmployeeID', null=True)),
                ('orderdate', models.DateTimeField(blank=True, db_column='OrderDate', null=True)),
                ('shipperid', models.IntegerField(blank=True, db_column='ShipperID', null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.IntegerField(db_column='ProductID', primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, db_column='ProductName', max_length=45, null=True)),
                ('supplierid', models.IntegerField(blank=True, db_column='SupplierID', null=True)),
                ('categoryid', models.IntegerField(blank=True, db_column='CategoryID', null=True)),
                ('unit', models.CharField(blank=True, db_column='Unit', max_length=45, null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('shipperid', models.IntegerField(db_column='ShipperID', primary_key=True, serialize=False)),
                ('shippername', models.CharField(blank=True, db_column='ShipperName', max_length=45, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=45, null=True)),
            ],
            options={
                'db_table': 'shippers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplierid', models.IntegerField(db_column='SupplierID', primary_key=True, serialize=False)),
                ('suppliername', models.CharField(blank=True, db_column='SupplierName', max_length=45, null=True)),
                ('contactname', models.CharField(blank=True, db_column='ContactName', max_length=45, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=45, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=45, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=45, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=45, null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeid', models.AutoField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=45, null=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=45, null=True)),
                ('birthdate', models.DateTimeField(blank=True, db_column='BirthDate', null=True)),
                ('photo', models.CharField(blank=True, db_column='Photo', max_length=45, null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=500, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
    ]
