# Generated by Django 2.2.6 on 2019-10-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': False},
        ),
    ]
